In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, precision_score

In [53]:
heart_df = pd.read_csv("heart.csv")

heart_df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [54]:
heart_df.info()
#heart_df.columns
heart_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [55]:
X= heart_df.drop("target", axis=1)
y= heart_df["target"]

In [56]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [57]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [58]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [59]:
y_train[y_train ==1]

132    1
75     1
59     1
93     1
6      1
      ..
121    1
20     1
71     1
106    1
102    1
Name: target, Length: 133, dtype: int64

In [60]:
y_test[y_test ==1]

111    1
60     1
9      1
119    1
33     1
5      1
101    1
45     1
118    1
46     1
125    1
152    1
25     1
146    1
73     1
109    1
139    1
42     1
17     1
76     1
90     1
24     1
57     1
92     1
77     1
137    1
116    1
7      1
78     1
63     1
82     1
104    1
Name: target, dtype: int64

In [61]:
model = LogisticRegression(max_iter=100)
model.fit(X_train, y_train)

# 4. Predict discrete class labels or continuous probabilities
predictions = model.predict(X_test)
#probabilities = model.predict_proba(X_test)

# 5. Evaluate the model performance
print("Accuracy:", accuracy_score(y_test, predictions)* 100 ,"%")

# 5. Evaluate the model performance
print("Precision:", precision_score(y_test, predictions) * 100 ,"%")

Accuracy: 88.52459016393442 %
Precision: 87.87878787878788 %

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## Using StandardScaler - try to find better result

In [62]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [63]:
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred)* 100 ,"%")
print("Precision:", precision_score(y_test, y_pred) * 100 ,"%")

Accuracy: 85.24590163934425 %
Precision: 87.09677419354838 %

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, precision_score, recall_score, f1_score


cm = confusion_matrix(y_test, y_pred)


print("Accuracy:", accuracy_score(y_test, y_pred)* 100 ,"%")
print("Precision:", precision_score(y_test, y_pred) * 100 ,"%")
print("f1_score:", f1_score(y_test, y_pred)* 100 ,"%")
print("recall_score:", recall_score(y_test, y_pred) * 100 ,"%")

Accuracy: 85.24590163934425 %
Precision: 87.09677419354838 %
f1_score: 85.71428571428571 %
recall_score: 84.375 %